name: .NET Core

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches: [ master ]
  schedule:
   - cron: "32 3 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: hadolint
        uses: reviewdog/action-hadolint@v1.50
        with:
          fail_on_error: ${{ ! startsWith(github.ref, 'refs/pull/') }}
          filter_mode: file

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=anydot/anybot
          VERSION=noop
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
              VERSION=edge
            fi
          fi
          echo ::set-output name=tags::${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Login to Docker
        uses: docker/login-action@v3.3.0
        with:
          username: anydot
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.15.0
        with:
          tags: ${{ steps.prep.outputs.tags }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          build-args: RELEASE=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Publish build status
        uses: guibranco/github-status-action-v2@v1.1.13
        if: ${{ always() }}
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Main build'
          state: ${{ job.status }}
          sha: ${{github.event.pull_request.head.sha || github.sha}}

