name: .NET Core

on:
  push:
    branches:
      - master
    tags:
      - v1.*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          fail_on_error: ${{ ! startsWith(github.ref, 'refs/pull/') }}
          filter_mode: file

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: anydot/anybot
          tag_with_ref: true
          tags: latest
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          build_args: RELEASE=${{ startsWith(github.ref, 'refs/tags/') }}
